
all:
	make -f Makefile.kista-xml
	make -f Makefile.xml-check
		
kista-xml:
	make -f Makefile.kista-xml

kista-xml-check:
	make -f Makefile.xml-check

install:
	make -f Makefile.kista-xml install
	make -f Makefile.xml-check install
		
clean:
	make -f Makefile.kista-xml clean
	make -f Makefile.xml-check clean
	
ultraclean:
	make -f Makefile.kista-xml ultraclean
	make -f Makefile.xml-check ultraclean
