EXTRACFLAGS = 
EXTRA_LIBS =

MODULE = run
SRCS = $(wildcard *.cpp)

OBJS = $(SRCS:.cpp=.o)

EXAMPLE_DIR=$(CURDIR)

ADD_INCLUDE_DIRS= 

include ../../Makefile.defs

#CFLAGS += 
CFLAGS +=  -DSC_INCLUDE_DYNAMIC_PROCESSES
